version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: blitz

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080